name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node: [18]
  
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Install Dependencies
      run: |
        npm ci

    - name: Build
      run: |
        npm run build

    - name: Deploy GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public